### PR TITLE
Make orgname clearer

### PR DESCRIPTION
**Pull request by jrmlhermitte**
Just because I made the silly mistake "jrmlhermitte" as github user name when trying to make GeRM a scinetific package.

I think we should write orgname to be clear.
For ex: we prob want nsls-ii-chx.github.io not yugangzhang.github.io/ in readme etc.

### CODE REVIEW

**Comment by danielballan** [comment]
I'd like to think about this for a minute. If our audience is "scientist with pile of scripts",  I think a user-based repo is a reasonable place to start. Seems to me that projects usually start in a personal repo (like [streamz](https://github.com/mrocklin/streamz)) and then get grow an org later.

Could we make it `github_user_or_org`?

**Comment by jrmlhermitte** [comment]
sure definitely we should discuss it.

If the user changes from username to org, they'll have to change the links in a few places.
I wonder if there might be a better way to do this?

Maybe we can add a "So I'm ready to move my repo from my personal to org, what do I do?" doc, and tell them which changes to make.
What do you think?

**Comment by danielballan** [comment]
My gut feeling is that if you are dealing with GitHub orgs or renaming things, you are an advanced GitHub user --- or you have access to one, as is the case with BL staff and DAMA. Not sure addressing this distinction or migration in detail fits well in the scope of this.

**Comment by tacaswell** [comment]
I am also :-1: on this change.

**Comment by jrmlhermitte** [comment]
Sounds good. Should be for beginning user. Closing. thanks for input!

**Pull request closed without merging**
